### ISSUE TITLE
support FirefoxOS

### ISSUE THREAD

**Issue by bugwelle** [ajoslin/angular-scrolly#10]
Hello,
I'd like to use `angular-scrolly` in a FirefoxOS-app. But you only support `webkit`.

You could something like [this](http://davidwalsh.name/vendor-prefix) to detect the vendor prefix:

``` js
var prefix = (function () {
  var styles = window.getComputedStyle(document.documentElement, ''),
    pre = (Array.prototype.slice
      .call(styles)
      .join('') 
      .match(/-(moz|webkit|ms)-/) || (styles.OLink === '' && ['', 'o'])
    )[1],
    dom = ('WebKit|Moz|MS|O').match(new RegExp('(' + pre + ')', 'i'))[1];
  return {
    dom: dom,
    lowercase: pre,
    css: '-' + pre + '-',
    js: pre[0].toUpperCase() + pre.substr(1)
  };
})();
```

Regards,
Andre

**Comment by ajoslin** [comment]
The newest version should work with firefox, lemme know. 

We use $sniffer service now (what angular uses in ngAnimate for prefixes) https://github.com/ajoslin/angular-scrolly/blob/master/src/services/transformer.js#L54-L57

**Comment by bugwelle** [comment]
Oh, :+1: 
didn't see that. I think I had the old code...

**Comment by bugwelle** [comment]
Well, seems that it doesn't work, yet.
I get this error:

`$window.getComputedStyle(raw)[transformProp] is undefined`

This is because the prefix is lower case, which makes sense for Webkit Browsers, but in Firefox the transformProp should be `MozTransform`instead of `mozTransform`.

This comment may be useful: http://davidwalsh.name/vendor-prefix#comment-48255
Please make the first letter of the prefix of `transformProp` uppercase. This works fine in Chrome ;)

**Comment by ajoslin** [comment]
Fixed :-)

And we now have unit tests on travis in all the browsers to prove it !

https://travis-ci.org/ajoslin/angular-scrolly/builds/9655008

Woohoo :-)
