### ISSUE TITLE
body has wrong position

### ISSUE THREAD

**Issue by bugwelle** [ajoslin/angular-scrolly#15]
Hello,
I noticed that the body has `transform: translate3d(0, 200px, 0);`. Only problem: When the content isn't high enough, there's a 200px gap.

In the demo file, reduce the number of list items to ten. Then it looks like this:

![scrolly](https://f.cloud.github.com/assets/1667306/870639/76c63948-f832-11e2-8b10-31efcddbcd43.jpg)

**Comment by ajoslin** [comment]
Yeah, I committed way too soon - I'll remove that hack and just use
mousewheel instead.

**Comment by ajoslin** [comment]
OK, latest commit won't work for desktop - but it will fix this :-)

Hopefully later today I can get mousewheel and arrow keys and spacebar
scroll working.

**Comment by bugwelle** [comment]
Thanks :)
After building angular-scrolly, I get an error which says that `checkBoundaries is undefined`.

Please replace this:

`checkBoundaries()`

with this:

`self.checkBoundaries()`

in your code :) That fixed it.
