### ISSUE TITLE
Range slider / custom select

### ISSUE THREAD

**Issue by kschio** [ajoslin/angular-scrolly#20]
Hi there,

I actually use angular-jqm: 

https://github.com/angular-widgets/angular-jqm

which has angular-scrolly included. 

The main problem is that I can't drag the range slider handle or scroll through the options in my custom select while using scrolly. If I remove scrolly there is no problem with using the range slider handle or my custom select.

At this point I'm just not sure why the range slider handle is not draggable or why I can't scroll through my custom select options while using scrolly. Maybe scrolly is preventing it.

Any ideas?

Thanks in advance

**Comment by ajoslin** [comment]
I had a feature like this but forgot about it and it got broken.  Now implemented with tests in latest push to master.

http://ajoslin.github.io/angular-scrolly/#/api/ajoslin.scrolly.directive:scrollyDraggerIgnore
https://github.com/ajoslin/angular-scrolly/blob/master/src/directives/scrolly-dragger-ignore.js
https://github.com/ajoslin/angular-scrolly/blob/master/src/services/dragger.js#L181-L185

Lemme know how it works for you.

**Comment by kschio** [comment]
Hi Andy,

thanks a lot for the fast response, it works fine for me! I added the changes to the angular-jqm and started to use the new directive on the elements I needed to ignore.

Thanks again
