### ISSUE TITLE
[Question] only rendering {{number of items that fit on screen}}?

### ISSUE THREAD

**Issue by hsdk123** [ajoslin/angular-scrolly#4]
The overview in the docs states that you built this hoping to implement "virtual scrolling" so that: `no matter how many items are in a list, only {{number of items that fit on screen}} are ever actually rendered`

Is this what `scrolly-scroll` is currently doing, or is it a final aim? I'm confused as to whether or not this is just rendering all elements but merely keeping the content outside scrolly-scroll intact in the same position on screen. If you have the time, it would be nice if you could add more explanation to the current readme.md.

**Comment by ajoslin** [comment]
Virtual scrolling is not done yet, I do plan to add a directive for it.  But I won't have time for another week or so.

With fake transform-scrolling, we have the capability to do virtual scrolling on mobile.  Without fake-scrolling, native phone scroll events are not enough to do virtual scrolling.

So it's like I've built the first block of the tower :-)

**Comment by hsdk123** [comment]
Thanks, that's cleared everything :) Looking forward to updates!
