### ISSUE TITLE
doesn't work with jQuery

### ISSUE THREAD

**Issue by bugwelle** [ajoslin/angular-scrolly#9]
In my project one plugin requires jQuery.
I noticed (it took me a while to figure out why) that angular-scrolly does not work with jQuery.

It's easy to fix this. Simply add

``` js
e = e.originalEvent || e;
```

to these lines in [dragger.js](https://github.com/ajoslin/angular-scrolly/blob/master/src/services/dragger.js):
- 226
- 262
- 296

Regards,
Andre

**Comment by bugwelle** [comment]
I think commit 8249eaf25049025a014e9439e8febb0b5e190100 fixed this.

**Comment by ajoslin** [comment]
ah yes, i did really bad on splitting up commit messages on that commit lol :-)

**Comment by bugwelle** [comment]
:D No problem.
Thanks for fixing that. I'll test the new version tomorrow. `angular-scrolly` works currently much better than `ng-iScroll` (1.2b). :+1:
